### ISSUE TITLE
Integrate api.data.gov 

### ISSUE THREAD

**Issue by gbinal** [18F/autoapi#18]

**Comment by jmcarp** [comment]
Working on this now. In the interest of building something we can easily automate, I propose the following:
- Client APIs live at https://api.data.gov/api-program/<client_name>`
- New APIs are added to api.data.gov via its API

Based on discussion with @cmc333333 and @GUI, automatic provisioning of new APIs at custom domains that do SSL termination isn't an option yet (but can be revisited later on). For now, if agencies want their APIs to show up at `api.agency.gov` or `agency.gov/api`, they can add a redirect to our URLs.

**Comment by jmcarp** [comment]
API Umbrella provisioning script added in 4493fb04495b1e7befe4c47f4e63ac9d490aaa52. There's still some work to do here, but we can now add an API to api.data.gov in one command.

**Comment by jmcarp** [comment]
URLs fixed in 47137685cb37d5f07efbfeb0ff544bfcf61ca6c5. This is good to go.
