### ISSUE TITLE
Generalized install instructions

### ISSUE THREAD

**Issue by catherinedevlin** [18F/autoapi#41]
To try out autoapi or as a prereq for deploying, users need to install autoapi locally, and I've run into problems trying that out (in my case, on a clean Ubuntu 15.10).  
- `invoke requirements` is not working; it complains about missing botocore as it tries to install boto, and if that is fixed in advance with `pip install botocore`, the next error is that `requests` is missing (although `requests` is listed in requirements.txt).  I'm not sure how `invoke requirements` works, but it doesn't seem to account for dependencies well, so I think that step should be replaced with `pip install -r requirements.txt`.
- autoapi uses Pandas, which depends on NumPy, which depends on a number of non-pure-Python dependencies like Fortran, which makes it hard to write general install instructions.  For example, on Ubuntu, a user's best bet is to `sudo apt-get install python3-numpy` or `sudo apt-get install python3-pandas` before setting up their virtualenv with `pyvenv --system-site-packages /my/autoapi/virtualenv`, but other platforms have different needs.  Possible approaches:
1. Write specific install instructions for all common platforms
2. Write instructions relying on a Python distro with built-in NumPy, like continuum.io's Anaconda.  (It's a free product, but does come from Continuum Analytics; is that OK?)
3. Build a Docker container users can run autoapi from
4. Give general principles and count on users to figure out the details

**Comment by jmcarp** [comment]
This all sounds useful, but I would actually defer writing much in the way of documentation until the design of the library is actually stable, since you may decide to make significant changes. I also think it's sufficient, and honestly preferable, to just link to the pandas docs for installation, instead of effectively rewriting them: http://pandas.pydata.org/pandas-docs/stable/install.html. That way, we don't have to endorse specific installers--I happen to prefer `miniconda` to `pyenv`, but I don't think that's relevant to the `autoapi` docs.

By the way, `invoke requirements` wraps `pip install -r requirements.txt`, so those commands should do exactly the same thing.

**Comment by catherinedevlin** [comment]
Ah, sorry, @jmcarp - I should have clarified that I didn't mean this as "please fix".  Rather, as I go through the installation with my ignorance pristine and complete, I'm trying to note everything I stumble over, so that I can eventually revise the instructions to account for those.  I thought maybe issues would be a good way to keep track of them for that.  I should self-assign and maybe tag them "backlog".

(I don't expect to make big changes to the library, either! - but I suppose I could be wrong.)

And that's a good idea to delegate Pandas install instructions to its own documentation, thanks.

**Comment by catherinedevlin** [comment]
> By the way, invoke requirements wraps pip install -r requirements.txt, so those commands should do exactly the same thing.

I see... and yet they are acting differently.  This is within a virtualenv; the aliases or shims or whatever (ok, I'm fuzzy on how virtualenv does its magic) that virtualenv creates must not affect `invoke.run`.  

```
    $ pyvenv --system-site-packageKv/ve/autoapi
    $ . v/ve/autoapi/bin/activate
    (autoapi) $ cd /share/autoapi/
    (autoapi) $ pip install invoke
    Downloading/unpacking invoke
      Downloading invoke-0.12.2-py2.py3-none-any.whl (166kB): 166kB downloaded
    Installing collected packages: invoke
    *** Error compiling '/tmp/pip-build-0b2aepnj/invoke/invoke/vendor/yaml2/constructor.py'...
      File "/tmp/pip-build-0b2aepnj/invoke/invoke/vendor/yaml2/constructor.py", line 130
        except TypeError, exc:
                ^
    SyntaxError: invalid syntax

    *** Error compiling '/tmp/pip-build-0b2aepnj/invoke/invoke/vendor/yaml2/reader.py'...
      File "/tmp/pip-build-0b2aepnj/invoke/invoke/vendor/yaml2/reader.py", line 158
        except UnicodeDecodeError, exc:
                     ^
    SyntaxError: invalid syntax

    *** Error compiling '/tmp/pip-build-0b2aepnj/invoke/invoke/vendor/yaml2/resolver.py'...
      File "/tmp/pip-build-0b2aepnj/invoke/invoke/vendor/yaml2/resolver.py", line 171
        re.compile(ur'''^(?:yes|Yes|YES|no|No|NO
                |true|True|TRUE|false|False|FALSE
                |on|On|ON|off|Off|OFF)$''', re.X),


                             ^
    SyntaxError: invalid syntax

    *** Error compiling '/tmp/pip-build-0b2aepnj/invoke/invoke/vendor/yaml2/scanner.py'...
      File "/tmp/pip-build-0b2aepnj/invoke/invoke/vendor/yaml2/scanner.py", line 1427
        except UnicodeDecodeError, exc:
                     ^
    SyntaxError: invalid syntax

    Successfully installed invoke
    Cleaning up...
    (autoapi) $ piKp -KV
    pip 1.5.6 from /home/vagrant/v/ve/autoapi/lib/python3.4/site-packages (python 3.4)
    (autoapi) $ invoke require
    Traceback (most recent call last):
      File "/home/vagrant/v/ve/autoapi/bin/invoke", line 11, in <module>
        sys.exit(program.run())
      File "/home/vagrant/v/ve/autoapi/lib/python3.4/site-packages/invoke/program.py", line 269, in run
        self._parse(argv)
      File "/home/vagrant/v/ve/autoapi/lib/python3.4/site-packages/invoke/program.py", line 323, in _parse
        self.load_collection()
      File "/home/vagrant/v/ve/autoapi/lib/python3.4/site-packages/invoke/program.py", line 471, in load_collection
        coll = loader.load(coll_name) if coll_name else loader.load()
      File "/home/vagrant/v/ve/autoapi/lib/python3.4/site-packages/invoke/loader.py", line 53, in load
        module = imp.load_module(name, fd, path, desc)
      File "/usr/lib/python3.4/imp.py", line 235, in load_module
        return load_source(name, filename, file)
      File "/usr/lib/python3.4/imp.py", line 171, in load_source
        module = methods.load()
      File "<frozen importlib._bootstrap>", line 1220, in load
      File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 1129, in _exec
      File "<frozen importlib._bootstrap>", line 1471, in exec_module
      File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
      File "/share/autoapi/tasks.py", line 5, in <module>
        import aws
      File "/share/autoapi/aws.py", line 7, in <module>
        import boto3
    ImportError: No module named 'boto3'
    (autoapi) $ pip install -r reqKpip install -r requirements.txt
    Downloading/unpacking git+https://github.com/jmcarp/sandman@develop (from -r requirements.txt (line 11))
      Cloning https://github.com/jmcarp/sandman (to develop) to /tmp/pip-fduurij8-build
      Running setup.py (path:/tmp/pip-fduurij8-build/setup.py) egg_info for package from git+https://github.com/jmcarp/sandman@develop
```

(snipping nine bazillion lines.  Completes successfully.)
