### ISSUE TITLE
Create 3 new autoapi instances

### ISSUE THREAD

**Issue by gbinal** [18F/autoapi#45]
https://sec-autoapi.apps.cloud.gov/
https://nara-autoapi.apps.cloud.gov/
https://ed-autoapi.apps.cloud.gov/

With each having discrete S3 buckets.

**Comment by catherinedevlin** [comment]
@gbinal : Should we close this ticket?  I don't think it applies anymore.

**Comment by gbinal** [comment]
👍  - yep!
