### ISSUE TITLE
Does this accept .xls? 

### ISSUE THREAD

**Issue by gbinal** [18F/autoapi#6]
Not urgent but at some point would be good to answer.  

We shouldn't devote development time to adding if not.

**Comment by jmcarp** [comment]
This is supported, along with a handful of other formats:
`SUPPORTED_FORMATS = ['fixed', 'xls', 'xlsx', 'csv', 'json', 'geojson', 'ndjson']`

**Comment by gbinal** [comment]
Roger.  Sorry, but what's `fixed`?

**Comment by jmcarp** [comment]
Had to look this one up. Fixed means fixed-width format, where columns are defined by the number of characters from the beginning of the line:

```
name      value
foo       bar
foobar    baz
```

In this example, the first column begins at character 0, and the second begins at character 11.

**Comment by gbinal** [comment]
Definitely didn't know that was a thing.  Thanks!
