### ISSUE TITLE
Query parameters in readme are confusing

### ISSUE THREAD

**Issue by toolness** [18F/autoapi#60]
The query parameters section of the readme currently lists the following:

```
 * ?[columnheader1]=[value1]&[columnheader1]=[value2]  (returns results that have value1 OR value2)
 * ?[columnheader1]=[value1]&[columnheader3]=[value4]  (returns results that have both value1 and value2)
```

I'm confused by this; the second line doesn't even _mention_ `value2` anywhere on it, yet it's supposed to return results that include it?

**Comment by gbinal** [comment]
:)  Totally agree it can and should be better.  

My suggestion is to hold for a bit until we've got an instance that you're playing with and we can hammer out better language together.  My ideal would also be to take a simple 20 cell dataset, host it, and link to a bunch of example calls along with the documentation.

**Comment by vrajmohan** [comment]
Closing as this issue is covered by #51.
